PROPERTY_TYPE_HOUSE = "HOUSE"
PROPERTY_TYPE_DUPLEX = "DUPLEX"
PROPERTY_TYPE_TOWN_HOUSE = "TOWNHOUSE"
PROPERTY_TYPE_LAND = "LAND"

PROPERTY_DASHBOARD_COLUMNS = {
    "address": "Property Address",
    "state": "State",
    "suburb": "Suburb",
    "postcode": "Post Code",
    "advertised_price": "Advertised Price",
    "bed": "Bed",
    "bath": "Bath",
    "car": "Car",
    "size": "Size (m2)",
    "frontage": "Frontage (m)",
    "council": "Council",
    "date_listed": "Date Listed",
    "days_on_market": "Days on Market",
    "a_subdivision_gross_profit_on_cost": "a-Subdivision",
    "b_subdivision_reno_gross_profit_on_cost": "b-Subdivision & Reno",
    "c_demolish_subdivision_gross_profit_on_cost": "c-Demolish & Subdivision",
    "d_demolish_duplex_gross_profit_on_cost": "d-Demolish & Duplex",
    "e_subdivision_reno_duplex_gross_profit_on_cost": "e-Subdivision & Reno & Duplex",
    "f_demolish_townhouse_gross_profit_on_cost": "f-Demolish & Townhouse",
    "highest_margin": "Highest margin",
    "feasible": "Feasible"
}

PROPERTY_DETAIL_COLUMNS = {
    "address": "Property address",
    "advertised_price": "Listed Price",
    "lower_price": "Property value - Low",
    "mid_price": "Property value - Medium",
    "upper_price": "Property value - High",
    "find_price": "Price used in feasibility",
    "size": "Site area (m2)",
    "home_size": "Home size (m2)",
    "useable_land": "Useable land",
    "min_lot_size_subdivision": "Minimum lot size subdivision (m2)",
    "min_lot_size_duplex": "Minimum lot size duplex (m2)",
    "min_frontage": "Minimum frontage (m2)",
    "bed": "Bed",
    "bath": "Bath",
    "car": "Car",
    "council": "Council",
    "zoning": "Zoning",
    "stamp_duty": "Stamp duty",
    "titles_office_transfer_on_purchase": "Titles Office Transfer on Purchase",
    "rates_adjustments_at_settlement": "Rates Adjustments at Settlement",
    "conveyancing_fees": "Conveyancing Fees",
    "miscellaneous_bank_fees": "Miscellaneous Bank Fees",
    "mortgage_registration_fee": "Mortgage Registration Fee",
    "title_transfer_fee": "Title Transfer Fee",
    "bank_legal_fees_on_purchase": "Bank Legal Fees on Purchase",
    "bank_property_valuation": "Bank Property Valuation",
    "bank_loan_application_fee": "Bank Loan Application Fee",
    "insurance_on_existing_buildings": "Insurance on Existing Buildings",
    "rates": "Rates",
    "other": "Other",
    "residential_loan_lvr": "Residential loan LVR",
    "project_duration_months": "Project duration (months)",
    "interest_on_residential_loan": "Interest on residential loan",
    "rental_term_months": "Rental term (months)",
    "net_rental_income_per_week": "Net Rental income (per week)",
    "renovation_uplift": "Renovation uplift",
    "agents_commission": "Agents Commission",
    "advertising_and_marketing": "Advertising and marketing",
    "conveyancing_settlement_costs": "Conveyancing and Settlement costs",
    "rates_adjustment_on_settlement": "Rates adjustment on Settlement",
    "mortgage_discharge_fee": "Mortgage discharge fee",
    "register_discharge_titles_office": "Register discharge - Titles office",
    "gst_liability_on_sales": "Gst liability on sales",
    "input_credits": "Input credits",
    "civil_costs_per_block": "Civil Costs per Block",
    "demolition_costs": "Demolition Costs",
    "infrastructure_exceptional_costs": "Infrastructure & Exceptional Costs",
    "professional_fees_based_on_construction_cost": "Professional Fees (based on Construction Cost)",
    "contingencies_based_on_build_cost": "Contingencies (based on Build Cost)",
    "average_house_m2": "Average House m2",
    "build_cost_m2": "Build cost m2",
    "council_contributions_per_house": "Council Contributions - per House",
    "rates_utilities_land_tax": "Rates, Utilities & Land Tax",
    "months_to_finance": "Months to finance",
    "interest_on_construction_loan": "Interest on construction loan",
    "bank_fees": "Bank Fees",
    "brokers_fees": "Brokers Fees",
    "other_lending_costs": "Other Lending costs",
    "construction_deposit": "Construction deposit",
    "construction_loan_lvr": "Construction loan LVR",
    "renovation_costs": "Renovation costs",
    "investor_input": "Investor Input"
}
